/*
 * Copyright (c) 2016-2017 LabKey Corporation
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.labkey.gradle.plugin

import org.gradle.api.Plugin
import org.gradle.api.Project
import org.gradle.api.Task
import org.labkey.gradle.task.ServerSideJS
import org.labkey.gradle.util.GroupNames

/**
 * Creates javascript files for use on the server side.
 *
 * TODO clean does not clean out the files generated by serverSideJS
 */
class CoreScripts implements Plugin<Project>
{
    @Override
    void apply(Project project)
    {
        addTasks(project)
    }

    private void addTasks(Project project)
    {
        Task task = project.task("serverSideJS",
                group: GroupNames.CODE_GENERATION,
                description: "Concatenate javascript files for use on the server side",
                type: ServerSideJS
        )
        if (project.hasProperty("processModuleResources"))
            project.tasks.processModuleResources.dependsOn(task)
    }
}
