package org.labkey.gradle.plugin

import org.gradle.api.Plugin
import org.gradle.api.Project
import org.gradle.api.Task
import org.labkey.gradle.task.ServerSideJS
import org.labkey.gradle.util.GroupNames

/**
 * Creates javascript files for use on the server side.
 *
 * TODO clean does not clean out the files generated by serverSideJS
 */
class CoreScripts implements Plugin<Project>
{
    @Override
    void apply(Project project)
    {
        addTasks(project)
    }

    private void addTasks(Project project)
    {
        Task task = project.task("serverSideJS",
                group: GroupNames.CODE_GENERATION,
                description: "Concatenate javascript files for use on the server side",
                type: ServerSideJS
        )
        if (project.hasProperty("processResources"))
            project.tasks.processResources.dependsOn(task)
    }
}
